version: '3.11'

services:
  web:
    build: .
    command: bash -c "cd app && uvicorn main:app --reload --host 0.0.0.0"
    #command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
